/**
 * The part table, the files it describes, and the pose built from them.
 *
 * `src/render/catParts.ts` is generated by `scripts/cut-parts.py` from the art
 * sheet. Generated code and the files it describes drift the moment someone
 * regenerates one and not the other, and the symptom is not an error — it is a
 * limb an inch out of place, which reads as bad art rather than as stale data.
 * So the numbers are checked against the actual PNGs on disk.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { CAT_HEADS, CAT_LIMBS, CAT_PARTS, CAT_TAILS, type CatPartName } from '../src/render/catParts.ts';
import { STANDING } from '../src/render/CatSprite.ts';

const CAT_DIR = fileURLToPath(new URL('../public/cat', import.meta.url));

/**
 * Width and height straight out of the PNG header.
 *
 * Thirteen bytes of IHDR, which is always the first chunk. An image library
 * would be a dependency added to check a number this test can read itself.
 */
function pngSize(path: string): { width: number; height: number } {
  const buffer = readFileSync(path);
  expect(buffer.subarray(0, 8).toString('hex')).toBe('89504e470d0a1a0a');
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
}

const names = Object.keys(CAT_PARTS) as CatPartName[];

describe('the table and the files agree', () => {
  it('names twelve parts', () => {
    expect(names).toHaveLength(12);
  });

  it.each(names)('%s exists as a PNG', (name) => {
    expect(() => pngSize(join(CAT_DIR, `${name}.png`))).not.toThrow();
  });

  it.each(names)('%s is the size the table says', (name) => {
    const actual = pngSize(join(CAT_DIR, `${name}.png`));
    expect(actual).toEqual({
      width: CAT_PARTS[name].width,
      height: CAT_PARTS[name].height,
    });
  });

  it('has no PNG the table does not name', () => {
    // The direction that a per-name loop cannot catch: a part added to the
    // sheet, cut, and then never wired up. It would sit in `public/` looking
    // like a working asset and never draw.
    const onDisk = readdirSync(CAT_DIR)
      .filter((f) => f.endsWith('.png'))
      .map((f) => f.replace(/\.png$/, ''))
      .sort();
    expect(onDisk).toEqual([...names].sort());
  });
});

describe('the parts are grouped as the renderer expects', () => {
  it('has three expressions and no face layer', () => {
    // Faces are baked into the heads — see `CatSprite`. Three is the whole
    // expression vocabulary the art currently supports.
    expect(CAT_HEADS).toEqual(['head-open', 'head-closed', 'head-happy']);
  });

  it('has four tails', () => {
    expect(CAT_TAILS).toHaveLength(4);
  });

  it('has two arms and two legs', () => {
    expect([...CAT_LIMBS].sort()).toEqual(['arm-left', 'arm-right', 'leg-left', 'leg-right']);
  });

  it('measures a ball joint for every limb and for nothing else', () => {
    // The pivot only means something on a part that rotates. A ball anchor on
    // a torso would be a measurement of nothing, quietly used later.
    for (const name of names) {
      const isLimb = (CAT_LIMBS as readonly string[]).includes(name);
      expect(CAT_PARTS[name].ballAnchor === null).toBe(!isLimb);
    }
  });

  it.each(CAT_LIMBS)('puts %s’s ball joint at the top of the part', (limb) => {
    const anchor = CAT_PARTS[limb].ballAnchor;
    expect(anchor).not.toBeNull();
    const [x, y] = anchor!;
    // Near the middle horizontally, and in the top third — `ART-BRIEF.md` §4
    // rule 5. A ball measured lower down means the cut caught something else,
    // and every future rotation would swing about the wrong point.
    expect(x).toBeGreaterThan(0.25);
    expect(x).toBeLessThan(0.75);
    expect(y).toBeGreaterThan(0);
    expect(y).toBeLessThan(0.34);
  });
});

describe('the standing layout', () => {
  it('puts the head above the torso', () => {
    expect(STANDING.headY).toBeLessThan(0);
  });

  it('puts the feet below it', () => {
    expect(STANDING.legY).toBeGreaterThan(0);
  });

  it('sets the arms wider than the legs', () => {
    // The arms have to clear the torso's widest point or nothing of them shows;
    // the legs sit under the body. Reversed, the cat is knock-kneed with its
    // paws tucked inside its own belly, which is a thing that has to be looked
    // at to be noticed.
    expect(STANDING.armX).toBeGreaterThan(STANDING.legX);
  });

  it('scales every part to something visible', () => {
    for (const scale of [STANDING.headScale, STANDING.armScale, STANDING.legScale, STANDING.tailScale]) {
      expect(scale).toBeGreaterThan(0);
      expect(scale).toBeLessThanOrEqual(1);
    }
  });
});
